// Generated by rstantools.  Do not edit by hand.

/*
    jaspAcceptanceSampling is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    jaspAcceptanceSampling is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with jaspAcceptanceSampling.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_complex_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 41> locations_array__ =
  {" (found before start of program)",
  " (in 'complex', line 15, column 2 to column 32)",
  " (in 'complex', line 17, column 2 to column 26)",
  " (in 'complex', line 19, column 2 to column 20)",
  " (in 'complex', line 21, column 2 to column 24)",
  " (in 'complex', line 24, column 2 to column 15)",
  " (in 'complex', line 25, column 2 to column 15)",
  " (in 'complex', line 26, column 2 to column 18)",
  " (in 'complex', line 27, column 2 to column 18)",
  " (in 'complex', line 48, column 2 to column 13)",
  " (in 'complex', line 29, column 2 to column 26)",
  " (in 'complex', line 31, column 2 to column 24)",
  " (in 'complex', line 32, column 2 to column 40)",
  " (in 'complex', line 35, column 4 to column 54)",
  " (in 'complex', line 34, column 17 to line 36, column 3)",
  " (in 'complex', line 34, column 2 to line 36, column 3)",
  " (in 'complex', line 38, column 2 to column 24)",
  " (in 'complex', line 50, column 2 to column 54)",
  " (in 'complex', line 41, column 2 to column 58)",
  " (in 'complex', line 42, column 2 to column 47)",
  " (in 'complex', line 43, column 2 to column 34)",
  " (in 'complex', line 44, column 2 to column 49)",
  " (in 'complex', line 45, column 2 to column 25)",
  " (in 'complex', line 2, column 2 to column 17)",
  " (in 'complex', line 3, column 8 to column 9)",
  " (in 'complex', line 3, column 2 to column 26)",
  " (in 'complex', line 4, column 8 to column 9)",
  " (in 'complex', line 4, column 2 to column 26)",
  " (in 'complex', line 5, column 8 to column 9)",
  " (in 'complex', line 5, column 2 to column 26)",
  " (in 'complex', line 6, column 8 to column 9)",
  " (in 'complex', line 6, column 2 to column 28)",
  " (in 'complex', line 8, column 2 to column 31)",
  " (in 'complex', line 9, column 2 to column 31)",
  " (in 'complex', line 10, column 2 to column 31)",
  " (in 'complex', line 11, column 2 to column 33)",
  " (in 'complex', line 19, column 9 to column 12)",
  " (in 'complex', line 24, column 9 to column 10)",
  " (in 'complex', line 25, column 9 to column 10)",
  " (in 'complex', line 26, column 9 to column 12)",
  " (in 'complex', line 27, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_complex final : public model_base_crtp<model_complex> {
private:
  int T;
  std::vector<int> s;
  std::vector<int> n;
  std::vector<int> y;
  std::vector<double> temperature;
  double prior_theta1_a;
  double prior_theta1_b;
  double prior_sigma_sd;
  double prior_beta_scale;
  int z_raw_1dim__;
  int eta_1dim__;
public:
  ~model_complex() {}
  model_complex(stan::io::var_context& context__, unsigned int
                random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_complex_namespace::model_complex";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 23;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 23;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("s", "T", T);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "s", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      s = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 25;
      s = context__.vals_i("s");
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "s", s, 0);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("n", "T", T);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      n = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 27;
      n = context__.vals_i("n");
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "n", n, 0);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("y", "T", T);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      y = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 29;
      y = context__.vals_i("y");
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("temperature", "T", T);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "temperature", "double",
        std::vector<size_t>{static_cast<size_t>(T)});
      temperature = std::vector<double>(T,
                      std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 31;
      temperature = context__.vals_r("temperature");
      current_statement__ = 32;
      context__.validate_dims("data initialization", "prior_theta1_a",
        "double", std::vector<size_t>{});
      prior_theta1_a = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 32;
      prior_theta1_a = context__.vals_r("prior_theta1_a")[(1 - 1)];
      current_statement__ = 32;
      stan::math::check_greater_or_equal(function__, "prior_theta1_a",
        prior_theta1_a, 0);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "prior_theta1_b",
        "double", std::vector<size_t>{});
      prior_theta1_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 33;
      prior_theta1_b = context__.vals_r("prior_theta1_b")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "prior_theta1_b",
        prior_theta1_b, 0);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "prior_sigma_sd",
        "double", std::vector<size_t>{});
      prior_sigma_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 34;
      prior_sigma_sd = context__.vals_r("prior_sigma_sd")[(1 - 1)];
      current_statement__ = 34;
      stan::math::check_greater_or_equal(function__, "prior_sigma_sd",
        prior_sigma_sd, 0);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "prior_beta_scale",
        "double", std::vector<size_t>{});
      prior_beta_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 35;
      prior_beta_scale = context__.vals_r("prior_beta_scale")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "prior_beta_scale",
        prior_beta_scale, 0);
      current_statement__ = 36;
      z_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 36;
      z_raw_1dim__ = (T - 1);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("z_raw", "T - 1", z_raw_1dim__);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("nu", "T", T);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("mu", "T", T);
      current_statement__ = 39;
      eta_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 39;
      eta_1dim__ = (T - 1);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("eta", "T - 1", eta_1dim__);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("theta", "T", T);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + z_raw_1dim__ + 1;
  }
  inline std::string model_name() const final {
    return "model_complex";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_complex_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ theta1 = DUMMY_VAR__;
      current_statement__ = 1;
      theta1 = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      local_scalar_t__ sigma_eta = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_eta = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> z_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(z_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 3;
      z_raw = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(z_raw_1dim__);
      local_scalar_t__ beta_temperature = DUMMY_VAR__;
      current_statement__ = 4;
      beta_temperature = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(eta_1dim__,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(eta, stan::math::multiply(sigma_eta, z_raw),
        "assigning variable eta");
      current_statement__ = 11;
      stan::model::assign(nu, stan::math::logit(theta1),
        "assigning variable nu", stan::model::index_uni(1));
      current_statement__ = 12;
      stan::model::assign(nu,
        stan::math::add(
          stan::model::rvalue(nu, "nu", stan::model::index_uni(1)),
          stan::math::cumulative_sum(eta)), "assigning variable nu",
        stan::model::index_min_max(2, T));
      current_statement__ = 15;
      for (int t = 1; t <= T; ++t) {
        current_statement__ = 13;
        stan::model::assign(mu,
          (stan::model::rvalue(nu, "nu", stan::model::index_uni(t)) +
          (beta_temperature *
          stan::model::rvalue(temperature, "temperature",
            stan::model::index_uni(t)))), "assigning variable mu",
          stan::model::index_uni(t));
      }
      current_statement__ = 16;
      stan::model::assign(theta, stan::math::inv_logit(mu),
        "assigning variable theta");
      {
        current_statement__ = 18;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(theta1,
                         prior_theta1_a, prior_theta1_b));
        current_statement__ = 19;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_eta, 0,
                         prior_sigma_sd));
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(z_raw, 0, 1));
        current_statement__ = 21;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(beta_temperature, 0,
                         prior_beta_scale));
        current_statement__ = 22;
        lp_accum__.add(stan::math::binomial_lpmf<propto__>(y, n, theta));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_complex_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double theta1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      theta1 = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      double sigma_eta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma_eta = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> z_raw =
        Eigen::Matrix<double,-1,1>::Constant(z_raw_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      z_raw = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(z_raw_1dim__);
      double beta_temperature = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      beta_temperature = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double,-1,1> nu =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> eta =
        Eigen::Matrix<double,-1,1>::Constant(eta_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> theta =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(theta1);
      out__.write(sigma_eta);
      out__.write(z_raw);
      out__.write(beta_temperature);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 10;
      stan::model::assign(eta, stan::math::multiply(sigma_eta, z_raw),
        "assigning variable eta");
      current_statement__ = 11;
      stan::model::assign(nu, stan::math::logit(theta1),
        "assigning variable nu", stan::model::index_uni(1));
      current_statement__ = 12;
      stan::model::assign(nu,
        stan::math::add(
          stan::model::rvalue(nu, "nu", stan::model::index_uni(1)),
          stan::math::cumulative_sum(eta)), "assigning variable nu",
        stan::model::index_min_max(2, T));
      current_statement__ = 15;
      for (int t = 1; t <= T; ++t) {
        current_statement__ = 13;
        stan::model::assign(mu,
          (stan::model::rvalue(nu, "nu", stan::model::index_uni(t)) +
          (beta_temperature *
          stan::model::rvalue(temperature, "temperature",
            stan::model::index_uni(t)))), "assigning variable mu",
          stan::model::index_uni(t));
      }
      current_statement__ = 16;
      stan::model::assign(theta, stan::math::inv_logit(mu),
        "assigning variable theta");
      if (emit_transformed_parameters__) {
        out__.write(nu);
        out__.write(mu);
        out__.write(eta);
        out__.write(theta);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      int y_pred = std::numeric_limits<int>::min();
      current_statement__ = 17;
      y_pred = (stan::model::rvalue(y, "y", stan::model::index_uni(T)) +
        stan::math::binomial_rng(
          (stan::model::rvalue(s, "s", stan::model::index_uni(T)) -
          stan::model::rvalue(n, "n", stan::model::index_uni(T))),
          stan::model::rvalue(theta, "theta", stan::model::index_uni(T)),
          base_rng__));
      out__.write(y_pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ theta1 = DUMMY_VAR__;
      current_statement__ = 1;
      theta1 = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, theta1);
      local_scalar_t__ sigma_eta = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_eta = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_eta);
      Eigen::Matrix<local_scalar_t__,-1,1> z_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(z_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(z_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(z_raw_1dim__),
        "assigning variable z_raw");
      out__.write(z_raw);
      local_scalar_t__ beta_temperature = DUMMY_VAR__;
      current_statement__ = 4;
      beta_temperature = in__.read<local_scalar_t__>();
      out__.write(beta_temperature);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "theta1", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma_eta",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "z_raw", "double",
        std::vector<size_t>{static_cast<size_t>(z_raw_1dim__)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "beta_temperature",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ theta1 = DUMMY_VAR__;
      current_statement__ = 1;
      theta1 = context__.vals_r("theta1")[(1 - 1)];
      out__.write_free_lub(0, 1, theta1);
      local_scalar_t__ sigma_eta = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_eta = context__.vals_r("sigma_eta")[(1 - 1)];
      out__.write_free_lb(0, sigma_eta);
      Eigen::Matrix<local_scalar_t__,-1,1> z_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(z_raw_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_raw_flat__;
        current_statement__ = 3;
        z_raw_flat__ = context__.vals_r("z_raw");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= z_raw_1dim__; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(z_raw, z_raw_flat__[(pos__ - 1)],
            "assigning variable z_raw", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z_raw);
      local_scalar_t__ beta_temperature = DUMMY_VAR__;
      current_statement__ = 4;
      beta_temperature = context__.vals_r("beta_temperature")[(1 - 1)];
      out__.write(beta_temperature);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"theta1", "sigma_eta", "z_raw",
                "beta_temperature"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"nu", "mu", "eta", "theta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"y_pred"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(z_raw_1dim__)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{static_cast<size_t>(eta_1dim__)},
             std::vector<size_t>{static_cast<size_t>(T)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "theta1");
    param_names__.emplace_back(std::string() + "sigma_eta");
    for (int sym1__ = 1; sym1__ <= z_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_raw" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "beta_temperature");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "nu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= eta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "y_pred");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "theta1");
    param_names__.emplace_back(std::string() + "sigma_eta");
    for (int sym1__ = 1; sym1__ <= z_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_raw" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "beta_temperature");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "nu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= eta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "y_pred");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_eta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(z_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"beta_temperature\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(eta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_pred\",\"type\":{\"name\":\"int\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_eta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(z_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"beta_temperature\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(eta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_pred\",\"type\":{\"name\":\"int\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + z_raw_1dim__) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((T + T) +
      eta_1dim__) + T));
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + z_raw_1dim__) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((T + T) +
      eta_1dim__) + T));
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_complex_namespace::model_complex;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_complex_namespace::profiles__;
}
#endif
#endif
